### ISSUE TITLE
Cannot Access the db in handlers?

### ISSUE THREAD

**Issue by zzzet** [mtharrison/hapi.js-in-action#15]
Here is the dbConneciton:

```
const Sqlite3 = require('sqlite3');

const db = new Sqlite3.Database('./dindin.sqlite');
```

I had use bind the db with `server.bind({ db: dbConnection })` but i dont know why i cannot access the `this.db` in handlers. According to book `[Hapi Js in Action]` and [server.bind](http://hapijs.com/api#serverbindcontext) it should be working. I had to use `server.app.db = dbConnection` and every handler i had to do something like `const db  = request.server.app.db` and works fine.. is there issue with server.bind in hapi js version 13.4.0 and I m loving ur book....

**Comment by mtharrison** [comment]
Which chapter/subsection are you working on? Is it chapter 2? There's a full example from that chapter here, it's working ok for me with hapi 13.4.0.

https://github.com/mtharrison/hapi.js-in-action/tree/master/CH02%20-%20Building%20an%20API/2.6/2.6.2

Perhaps you can compare that to your code. If you still have trouble, try to post more code here and I can help.

**Comment by zzzet** [comment]
i got it working with `server.app.db = dbConnection` but not with `server.bind({db: dbConnection })`.. May be there is issue with my code.. I will compare it. 

But is it ok if i use `server.app.db` too ?

**Comment by mtharrison** [comment]
Yes `server.app.db` works too.
